### ISSUE TITLE
Juste bravo

### ISSUE THREAD

**Issue by n0skill** [opatiny/RAT#2]
Hello !

J'ai vu l'installation au gymnase (je suis élève en passerelle DUBS du soir) et je voulais juste dire bravo pour cette installation ! Beau mélange de physique, d'electronique, de code, et d'art ! Et le tout sur github, wow !

:100:

**Comment by opatiny** [comment]
Salut!
Heureuse de voir qu'il y a des gens qui connaissent GitHub! Merci pour ton commentaire, c'est super sympa de voir que des gens comprennent! Mais au fait tu l'a vu fonctionner? Parce que comme je l'éteint tous les soirs...

**Comment by n0skill** [comment]
En fait, on a les cours le soir du Lundi au Jeudi. Et vendredi on a les cours l'après-midi. C'est à ce moment où je l'ai vu ^^

D'ailleurs, si tu est intéressée y'a a une association sur Lausanne dont je fait partie avec du matériel pour faire un peu de tout (perceuses, découpe laser, imprimates 3D, stations de soudure, etc.). On est un peu plus centré sur l'informatique/sécurité aussi.
 [Fixme Hackerspace](https://fixme.ch) et on partage les locaux avec le [fablab de renens](http://www.fablab-renens.ch/) qui eux font plus de projets "tangibles".

Hésites pas à venir visiter. Le mercredi c'est le jour "ouvert" où tout le monde peut découvrir l'assoc et ou on cause autour d'un burger, etc.

À plus !

**Comment by opatiny** [comment]
Tu connais Oscar? 
Je suis déjà membre de Hack et du Made... 
(Tu aurais un mail ou Telegram?)

**Comment by n0skill** [comment]
Yep je suis sur telegram: @noskill

Pis sinon oui je connais un Oscar qui est membre de Fixme. Il est dessinateur en génie civil, c'est peut-être le même
